### PR TITLE
Add new function to get the view index pid.

### PR DESCRIPTION
**Pull request by brkolla**
Refactored the code to add a new function to return index pid for a
given view and design document.

COUCHDB-3150

### CODE REVIEW

**Comment by brkolla** [comment]
@rnewson @davisp. Can you please review this too. This change is also related to triggering an update with stale=update_after

**Comment by rnewson** [comment]
The patch does what it says it should, so that's fine. I'm concerned about fabric calling directly into couch_mrview_util, though. In other applications, fabric for example, we insist on an 'entry' module to allow future refactorings. So, for fabric, other applications should only ever call functions in fabric.erl. I think we should adopt that pattern here. @davisp what do you think?

**Comment by brkolla** [comment]
Sounds like a good pattern to follow. I can add a function in `couch_mrview` and update `fabric_rpc` to call couch_mrview module, which in turn will call the function in couch_mrview_util.

**Comment by brkolla** [comment]
@rnewson Have updated the code to make sure that I call into couch_mrview module and not call directly into cocuh_mrview_util

**Comment by rnewson** [comment]
+1 but let's only merge once the other PR is ready to merge.

**Comment by brkolla** [comment]
Thanks @rnewson. I don't have committer permissions so would need help merging this and the other PR. Have asked Paul to look at the other PR and +1

**Comment by davisp** [comment]
+1 to this as well. The other review is second on my list for today.

**Pull request merged**
