### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by KlausTrainer**

### CODE REVIEW

**Comment by KlausTrainer** [comment]
Hm. Just tested again with a fresh clone of the repo on my local development machine, and the tests are all passing. Has anybody an idea why those two tests are failing on Travis CI?

**Comment by kxepal** [comment]
I suspect more and more this instruction:
```
- cp -r ../!(couchdb) ./src/couch_mrview
```
doesnt works correctly on travis OS. While I tested it for the first .travis files to make sure that it actually copies all the stuff, seems like I miss something oblivous...

**Comment by KlausTrainer** [comment]
I don't really understand the bang and parentheses part in `!(couchdb)`, and it doesn't seem to work on my Ubuntu Linux machine. Can you describe what exactly it is supposed to achieve?

**Comment by kxepal** [comment]
For me on Gentoo with bash it means copy everything except these objects. 

So initially on travis home directory we have the following layout (for mrview):
```
- include/
- priv/
- src/
- test/
- .travis
- LICENSE
```

Then we clone couchdb repo here into couchdb directory and runs configure there. But ./configure cannot checkout our PR code, so we need to overwrite it. To do that we need to copy all top level mrview code over couchdb/src/couch_mrview. But obliviously, we don't need to copy couchdb directory there too, so we cannot use simple wildcard, but something that will exclude exact directory. That's what `!(couchdb)` does.

**Comment by KlausTrainer** [comment]
Cool. Thanks for the explanation :)

**Pull request merged**
