### PR TITLE
Should close old fd after view compaction

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by iilyak** [comment]
The test case is in https://github.com/apache/couchdb-couch/pull/136

**Comment by eiri** [comment]
Good catch. +1

**Comment by kxepal** [comment]
+1

**Comment by davisp** [comment]
-1

This would throw a 500 at anyone that happened to be streaming from the view when compaction ended. Files are closed via checking monitors in couch_file here:

https://github.com/apache/couchdb-couch/blob/master/src/couch_file.erl#L445-L452

**Comment by rnewson** [comment]
agree with davisp. For this to be the right fix we would _never_ close a file after compaction, rather it seems like a subset.

Locally, OSX, I verified that compacting a view shard causes the fd to change for the file in question and the old fd no longer appears in lsof output.

Next step is to patch a cloudant production cluster with additional logging so we can find what must be a race condition. Log when we finish compaction (I think we have this one already), log when we decide whether or not to close an unmonitored couch_file (in either case).

**Pull request closed without merging**
